CMDB/urls.py
"""DevOps URL Configuration
"""
from django.urls import path
from . import views

app_name = 'cmdb'
urlpatterns = [
    # ex： /CMDB/
    path('', views.IndexView.as_view(), name='index'),
    path('index', views.IndexView.as_view(), name='index'),
    # ex： /CMDB/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex： /CMDB/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex： /CMDB/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # login
    path('login/', views.login, name='login'),
    # authin
    path('login/authin/', views.authin, name='authin'),

]

DevOps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cmdb/', include('CMDB.urls'))
]

CMDB/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('发布时间')

    # 定义对象
    def __str__(self):
        return self.question_text

    # 定义方法
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    # 定义对象
    def __str__(self):
        return self.choice_text

CMDB/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
# from django.http import HttpResponse
# from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from .models import Question, Choice
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'cmdb/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


# 问题首页
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # template = loader.get_template('cmdb/index.html')
#     context = {'latest_question_list': latest_question_list, }
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'cmdb/index.html', context)


class DetailView(generic.DetailView):
    model = Question
    template_name = 'cmdb/detail.html'


# 详情
# def detail(request, question_id):
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist!")
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'cmdb/detail.html', {'question': question})
#     # return HttpResponse("You're looking at question %s." % question_id)


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'cmdb/results.html'


# 结果
# def results(request, question_id):
#     # response = "You're looking at the results of question %s."
#     # return HttpResponse(response % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'cmdb/results.html', {'question': question})


# 投票
def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'cmdb/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('cmdb:results', args=(question.id,)))


@login_required
def index(request):
    # total_idc =Idc.objects.aggregate(Count('idc_name'))
    # idc_num = total_idc["idc_name__count"]
    # total_host = HostList.objects.aggregate(Count('hostname'))
    # host_num = total_host["hostname__count"]
    return render(request, 'cmdb/index.html', locals())


def login(request):
    return render(request, 'cmdb/login.html', locals())


@csrf_exempt
def authin(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
            auth.login(request, user)
            return render(request, 'cmdb/index.html', {'login_user': request.user})
    else:
            return render(request, 'cmdb/login.html', {'login_err': 'Wrong username or password'})

CMDB/templates/cmdb/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'cmdb:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>
</html>

CMDB/templates/cmdb/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CMDB管理系统</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/cmdb/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/cmdb/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/cmdb/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/cmdb/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">welcome for Lmanager</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="authin/">
                            <fieldset>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="username" id="username" name="username">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password" id="password" name="password">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">登录</button>
				<!--
			       <button type="submit" class="btn btn-primary btn-block">Sign in</button>
 				-->
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="/static/cmdb/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/cmdb/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/static/cmdb/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/static/cmdb/dist/js/sb-admin-2.js"></script>

</body>

</html>

CMDB/templates/cmdb/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
{#    {% load static %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'cmdb/style.css' %}">#}
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
{#    <tr>#}
{#        <td>{{ choice.choice_text }}</td>#}
{#        <td>{{ choice.votes }}</td>#}
{#    </tr>#}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'cmdb:detail' question.id %}">Vote again?</a>
</body>
</html>